version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'user'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '34233:3306'
    volumes:
      - ./script_mysql_init.sql:/docker-entrypoint-initdb.d/init.sql